name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: acglab-ghaction-nonproduction
      AWS_REGION: us-east-1
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credential@v2
        with:
          role-to-assume: arn:aws:iam::525180147276:role/github-actions-deep-dive-role
          role-session-name: acglabrolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run:
          npm ci
          npm run build
      - name: deploy
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read
        