name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-bd91d7a31aeea1a9638e14180-nonprodbucket-f8itp0bx2jxx
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credential@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run:
          npm ci
          npm run build
      - name: deploy
        run: aws s3 cp public s3://${{ env.BUSKET_NAME }}/ --recursive --acl public-read
        